### PR TITLE
MODPERMS-119 Release 5.13.0

### PR DESCRIPTION
**Pull request by craigmcnally**
## Purpose
Release v5.13.0

See https://issues.folio.org/browse/MODPERMS-119
See also: [JIRA filter](https://issues.folio.org/issues/?jql=project%20%3D%20MODPERMS%20AND%20status%20%3D%20Closed%20AND%20fixVersion%20%3D%205.13.0%20ORDER%20BY%20updated%20DESC%2C%20fixVersion%20DESC%2C%20priority%20DESC)

## Notes
* Assumes MODPERMS-126 (#118) will be merged into master and this branch before tagging/releasing.

### CODE REVIEW

**Review by adamdickmeiss — COMMENTED** [review]
Don't see MODPERMS-126 here. And you mentioned that was going to be part of it.

**Review by hjiebsco — APPROVED** [review]
Looks fine. Please add `MODPERMS-126` and also bump up POM version. Approve it in advance so you do not have to wait.

**Comment by craigmcnally** [comment]
> Don't see MODPERMS-126 here. And you mentioned that was going to be part of it.

Yeah, It was late - I'll make sure it makes it in

**Comment by adamdickmeiss** [comment]
Good - a lot of work for a "feature" release. I think the module as a whole should be called 6.0.0, because of tenantPermission 2.0. It could have notedd that Okapi 4.6.0 is required and that Okapi 4.7.0 is recommended. Furthermore that the new restrictions on permission set definitions.

**Pull request merged**
