### PR TITLE
Do not assign context to dummy permissions MODPERMS-133

### PR DESCRIPTION
**Pull request by adamdickmeiss**
Dummy permissions should not be assigned a context. They don't belong to the module where they happen to be referred to.

They should be assigned a context when they are really defined.

Furthermore the collision check in savePerms is wrong for. It checks if context is null and then assumes it's user-defined context.
If a permission has Mutable undefined or TRUE – then it'a user-defined permission.

This PR also makes it possible to use stock install.json for Okapi. OKAPI-985.

### CODE REVIEW

**Comment by craigmcnally** [comment]
> Dummy permissions should not be assigned a context. They don't belong to the module where they happen to be referred to.
They should be assigned a context when they are really defined.

I agree - this is a good catch.

**Comment by craigmcnally** [comment]
> Furthermore the collision check in savePerms is wrong for. It checks if context is null and then assumes it's user-defined context.
If a permission has Mutable undefined or TRUE – then it'a user-defined permission.

As we discussed before we didn't want to rely on mutable as the indicator that a permission is system-defined because it's currently possible for a user to create an immutable permission.

That said, your changes in MODPERMS-130 already go down this path, so I guess we've changed our mind here and should just be consistent.

**Comment by adamdickmeiss** [comment]
> > Furthermore the collision check in savePerms is wrong for. It checks if context is null and then assumes it's user-defined context.
> > If a permission has Mutable undefined or TRUE – then it'a user-defined permission.
> 
> As we discussed before we didn't want to rely on mutable as the indicator that a permission is system-defined because it's currently possible for a user to create an immutable permission.
> 
> That said, your changes in MODPERMS-130 already go down this path, so I guess we've changed our mind here and should just be consistent.

Here's a check without mutable .. this does not change test results.
```java
 if (!Boolean.TRUE.equals(foundPerm.getDummy()) && foundPerm.getModuleName() == null) {
```

I'm not sure it's prettier.. We have an existing database with Dummy (not moduleName).

**Comment by craigmcnally** [comment]
When I implemented the static permission migration stuff the agreement was at the time to upgrade mod-permissions first, which in conjunction with the latest OKAPI code would result in all system-defined perms getting module context.  In that case using moduleName as an indicator that a permission was system or user defined was appropriate.  For various reasons, a lot has changed since then, including the agreement to not relying on mutable as that indicator...

**Comment by adamdickmeiss** [comment]
> When I implemented the static permission migration stuff the agreement was at the time to upgrade mod-permissions first, which in conjunction with the latest OKAPI code would result in all system-defined perms getting module context. In that case using moduleName as an indicator that a permission was system or user defined was appropriate. For various reasons, a lot has changed since then, including the agreement to not relying on mutable as that indicator...

It does seem like we're stuck with mutable as an indicator. Just merged PR https://github.com/folio-org/mod-permissions/pull/113  assumes exactly that mutable is the indicator and transforms system perms to Deprecated. And not just for from version 1.1 to 2 - any time mod-permissions is enabled, if I read the PR correctly.

**Comment by craigmcnally** [comment]
> > When I implemented the static permission migration stuff the agreement was at the time to upgrade mod-permissions first, which in conjunction with the latest OKAPI code would result in all system-defined perms getting module context. In that case using moduleName as an indicator that a permission was system or user defined was appropriate. For various reasons, a lot has changed since then, including the agreement to not relying on mutable as that indicator...
> 
> It does seem like we're stuck with mutable as an indicator. Just merged PR #113 assumes exactly that mutable is the indicator and transforms system perms to Deprecated. And not just for from version 1.1 to 2 - any time mod-permissions is enabled, if I read the PR correctly.

Right, though I think we're also planning on making mutable a read-only field so this should be a one-time risk.  Going forward, users shouldn't be able to create immutable permissions.

**Review by hjiebsco — APPROVED** [review]

**Pull request merged**
